version: '3'

services:

  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker # which docker

# docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

  registry:
    image: registry
    container_name: registry
    restart: always
    ports:
      - 5001:5000
